hash-format = "sha256"

[[files]]
file = ".github/workflows/build.yml"

[[files]]
file = ".github/workflows/update.yml"

[[files]]
file = "README.md"

[[files]]
file = "src/faithful-32x.pw.toml"
metafile = true

[[files]]
file = "src/mods/3dskinlayers.pw.toml"
metafile = true

[[files]]
file = "src/mods/ad-astra.pw.toml"
metafile = true

[[files]]
file = "src/mods/advanced-generators.pw.toml"
metafile = true

[[files]]
file = "src/mods/advanced-netherite.pw.toml"
metafile = true

[[files]]
file = "src/mods/ae2.pw.toml"
metafile = true

[[files]]
file = "src/mods/aether.pw.toml"
metafile = true

[[files]]
file = "src/mods/ai-improvements.pw.toml"
metafile = true

[[files]]
file = "src/mods/alternate-current.pw.toml"
metafile = true

[[files]]
file = "src/mods/ambientsounds.pw.toml"
metafile = true

[[files]]
file = "src/mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "src/mods/applied-energistics-2-wireless-terminals.pw.toml"
metafile = true

[[files]]
file = "src/mods/aquaculture.pw.toml"
metafile = true

[[files]]
file = "src/mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "src/mods/attributefix.pw.toml"
metafile = true

[[files]]
file = "src/mods/bad-wither-no-cookie.pw.toml"
metafile = true

[[files]]
file = "src/mods/balm.pw.toml"
metafile = true

[[files]]
file = "src/mods/bdlib.pw.toml"
metafile = true

[[files]]
file = "src/mods/betterf3.pw.toml"
metafile = true

[[files]]
file = "src/mods/biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "src/mods/bookshelf-lib.pw.toml"
metafile = true

[[files]]
file = "src/mods/botarium.pw.toml"
metafile = true

[[files]]
file = "src/mods/building-gadgets.pw.toml"
metafile = true

[[files]]
file = "src/mods/canary.pw.toml"
metafile = true

[[files]]
file = "src/mods/carry-on.pw.toml"
metafile = true

[[files]]
file = "src/mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "src/mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "src/mods/chisels-bits.pw.toml"
metafile = true

[[files]]
file = "src/mods/chunk-loaders.pw.toml"
metafile = true

[[files]]
file = "src/mods/client-tweaks.pw.toml"
metafile = true

[[files]]
file = "src/mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "src/mods/clumps.pw.toml"
metafile = true

[[files]]
file = "src/mods/collective.pw.toml"
metafile = true

[[files]]
file = "src/mods/comforts.pw.toml"
metafile = true

[[files]]
file = "src/mods/common-capabilities.pw.toml"
metafile = true

[[files]]
file = "src/mods/content-creator-integration.pw.toml"
metafile = true

[[files]]
file = "src/mods/controlling.pw.toml"
metafile = true

[[files]]
file = "src/mods/cooking-for-blockheads.pw.toml"
metafile = true

[[files]]
file = "src/mods/coroutil.pw.toml"
metafile = true

[[files]]
file = "src/mods/corpse.pw.toml"
metafile = true

[[files]]
file = "src/mods/create-structures.pw.toml"
metafile = true

[[files]]
file = "src/mods/create.pw.toml"
metafile = true

[[files]]
file = "src/mods/creativecore.pw.toml"
metafile = true

[[files]]
file = "src/mods/creeper-overhaul.pw.toml"
metafile = true

[[files]]
file = "src/mods/croptopia-additions.pw.toml"
metafile = true

[[files]]
file = "src/mods/croptopia.pw.toml"
metafile = true

[[files]]
file = "src/mods/cucumber.pw.toml"
metafile = true

[[files]]
file = "src/mods/curios.pw.toml"
metafile = true

[[files]]
file = "src/mods/cyclic.pw.toml"
metafile = true

[[files]]
file = "src/mods/cyclops-core.pw.toml"
metafile = true

[[files]]
file = "src/mods/dark-paintings.pw.toml"
metafile = true

[[files]]
file = "src/mods/deeperdarker.pw.toml"
metafile = true

[[files]]
file = "src/mods/ding.pw.toml"
metafile = true

[[files]]
file = "src/mods/distanthorizons.pw.toml"
metafile = true

[[files]]
file = "src/mods/double-doors.pw.toml"
metafile = true

[[files]]
file = "src/mods/dungeon-crawl.pw.toml"
metafile = true

[[files]]
file = "src/mods/embeddium.pw.toml"
metafile = true

[[files]]
file = "src/mods/emi.pw.toml"
metafile = true

[[files]]
file = "src/mods/enchantment-descriptions.pw.toml"
metafile = true

[[files]]
file = "src/mods/enderio.pw.toml"
metafile = true

[[files]]
file = "src/mods/endrem.pw.toml"
metafile = true

[[files]]
file = "src/mods/entityculling.pw.toml"
metafile = true

[[files]]
file = "src/mods/epherolib.pw.toml"
metafile = true

[[files]]
file = "src/mods/extreme-reactors.pw.toml"
metafile = true

[[files]]
file = "src/mods/fallingtree.pw.toml"
metafile = true

[[files]]
file = "src/mods/farmers-delight.pw.toml"
metafile = true

[[files]]
file = "src/mods/farming-for-blockheads.pw.toml"
metafile = true

[[files]]
file = "src/mods/fastfurnace.pw.toml"
metafile = true

[[files]]
file = "src/mods/fastload.pw.toml"
metafile = true

[[files]]
file = "src/mods/fastsuite.pw.toml"
metafile = true

[[files]]
file = "src/mods/fastworkbench.pw.toml"
metafile = true

[[files]]
file = "src/mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "src/mods/flib.pw.toml"
metafile = true

[[files]]
file = "src/mods/flux-networks.pw.toml"
metafile = true

[[files]]
file = "src/mods/ftb-library-forge.pw.toml"
metafile = true

[[files]]
file = "src/mods/ftb-ultimine-forge.pw.toml"
metafile = true

[[files]]
file = "src/mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "src/mods/hammer-lib.pw.toml"
metafile = true

[[files]]
file = "src/mods/highlight.pw.toml"
metafile = true

[[files]]
file = "src/mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "src/mods/integrated-dynamics.pw.toml"
metafile = true

[[files]]
file = "src/mods/iron-chests.pw.toml"
metafile = true

[[files]]
file = "src/mods/iron-jetpacks.pw.toml"
metafile = true

[[files]]
file = "src/mods/jade.pw.toml"
metafile = true

[[files]]
file = "src/mods/jei.pw.toml"
metafile = true

[[files]]
file = "src/mods/just-zoom.pw.toml"
metafile = true

[[files]]
file = "src/mods/konkrete.pw.toml"
metafile = true

[[files]]
file = "src/mods/kotlin-for-forge.pw.toml"
metafile = true

[[files]]
file = "src/mods/macaws-bridges.pw.toml"
metafile = true

[[files]]
file = "src/mods/macaws-doors.pw.toml"
metafile = true

[[files]]
file = "src/mods/mcjtylib.pw.toml"
metafile = true

[[files]]
file = "src/mods/mekanism-additions.pw.toml"
metafile = true

[[files]]
file = "src/mods/mekanism-tools.pw.toml"
metafile = true

[[files]]
file = "src/mods/mekanism.pw.toml"
metafile = true

[[files]]
file = "src/mods/memoryleakfix.pw.toml"
metafile = true

[[files]]
file = "src/mods/mob-grinding-utils.pw.toml"
metafile = true

[[files]]
file = "src/mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "src/mods/more-mobs.pw.toml"
metafile = true

[[files]]
file = "src/mods/mouse-tweaks.pw.toml"
metafile = true

[[files]]
file = "src/mods/mrcrayfish-furniture-mod.pw.toml"
metafile = true

[[files]]
file = "src/mods/mystical-agradditions.pw.toml"
metafile = true

[[files]]
file = "src/mods/mystical-agriculture.pw.toml"
metafile = true

[[files]]
file = "src/mods/netherportalfix.pw.toml"
metafile = true

[[files]]
file = "src/mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "src/mods/no-telemetry.pw.toml"
metafile = true

[[files]]
file = "src/mods/notenoughcrashes.pw.toml"
metafile = true

[[files]]
file = "src/mods/notrample.pw.toml"
metafile = true

[[files]]
file = "src/mods/nyctophobia-dread.pw.toml"
metafile = true

[[files]]
file = "src/mods/oculus.pw.toml"
metafile = true

[[files]]
file = "src/mods/overloaded-armor-bar.pw.toml"
metafile = true

[[files]]
file = "src/mods/patchouli.pw.toml"
metafile = true

[[files]]
file = "src/mods/placebo.pw.toml"
metafile = true

[[files]]
file = "src/mods/projecte.pw.toml"
metafile = true

[[files]]
file = "src/mods/pure-discs-trails-tales.pw.toml"
metafile = true

[[files]]
file = "src/mods/raised.pw.toml"
metafile = true

[[files]]
file = "src/mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "src/mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "src/mods/resourcify.pw.toml"
metafile = true

[[files]]
file = "src/mods/rftools-base.pw.toml"
metafile = true

[[files]]
file = "src/mods/rftools-builder.pw.toml"
metafile = true

[[files]]
file = "src/mods/rftools-dimensions.pw.toml"
metafile = true

[[files]]
file = "src/mods/rftools-power.pw.toml"
metafile = true

[[files]]
file = "src/mods/rftools-storage.pw.toml"
metafile = true

[[files]]
file = "src/mods/rftools-utility.pw.toml"
metafile = true

[[files]]
file = "src/mods/saturn.pw.toml"
metafile = true

[[files]]
file = "src/mods/scalable-cats-force.pw.toml"
metafile = true

[[files]]
file = "src/mods/scaling-health.pw.toml"
metafile = true

[[files]]
file = "src/mods/seamless-loading-screen.pw.toml"
metafile = true

[[files]]
file = "src/mods/searchables.pw.toml"
metafile = true

[[files]]
file = "src/mods/security-craft.pw.toml"
metafile = true

[[files]]
file = "src/mods/serene-seasons.pw.toml"
metafile = true

[[files]]
file = "src/mods/silent-lib.pw.toml"
metafile = true

[[files]]
file = "src/mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "src/mods/snow-under-trees.pw.toml"
metafile = true

[[files]]
file = "src/mods/solar-flux-reborn.pw.toml"
metafile = true

[[files]]
file = "src/mods/sophisticated-backpacks.pw.toml"
metafile = true

[[files]]
file = "src/mods/sophisticated-core.pw.toml"
metafile = true

[[files]]
file = "src/mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "src/mods/spark.pw.toml"
metafile = true

[[files]]
file = "src/mods/spawn-animations.pw.toml"
metafile = true

[[files]]
file = "src/mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "src/mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "src/mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "src/mods/the-twilight-forest.pw.toml"
metafile = true

[[files]]
file = "src/mods/torchmaster.pw.toml"
metafile = true

[[files]]
file = "src/mods/trash-cans.pw.toml"
metafile = true

[[files]]
file = "src/mods/wavey-capes.pw.toml"
metafile = true

[[files]]
file = "src/mods/waystones.pw.toml"
metafile = true

[[files]]
file = "src/mods/weather-storms-tornadoes.pw.toml"
metafile = true

[[files]]
file = "src/mods/what-are-they-up-to.pw.toml"
metafile = true

[[files]]
file = "src/mods/worldedit.pw.toml"
metafile = true

[[files]]
file = "src/mods/xaeros-minimap-world-map-waystones-compatibility-forge.pw.toml"
metafile = true

[[files]]
file = "src/mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "src/mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "src/mods/xnet.pw.toml"
metafile = true

[[files]]
file = "src/mods/zerocore.pw.toml"
metafile = true

[[files]]
file = "src/resourcepacks/faithful-32x.pw.toml"
metafile = true

[[files]]
file = "src/resourcepacks/fast-better-grass.pw.toml"
metafile = true

[[files]]
file = "src/resourcepacks/unique-dark-gui-modded-compat.pw.toml"
metafile = true

[[files]]
file = "src/resourcepacks/unique-dark.pw.toml"
metafile = true
