name = "velvet"
author = "Checksum"
version = "1.1.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0711651294f10ca32abc275383fb586f54c25033b2ad9def5179a1e85f0efd6e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
