name = "velvet"
author = "Checksum"
version = "1.1.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b356057ebe4aa9899769419f0eac8341b2ad6d224096728a3c51499dea575fb8"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
