name = "velvet"
author = "Checksum"
version = "1.1.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9430e513e25b44ee30c33396355dc925dda32bbd3c0ee73f1929a14f4d83f43"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
