name: Refresh Packwiz Index

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Refresh packwiz index
        run: packwiz refresh

      - name: Commit and push changes
        run: |
          git config --local user.email "me@checksum.space"
          git config --local user.name "Checksum"
          git add .
          git commit -am "chore: refresh index"
          git push
