name: Release Artifacts

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Build for Modrinth
        run: packwiz modrinth export

      - name: Build for CurseForge
        run: packwiz curseforge export

      - name: Upload CurseForge modpack
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.event.release.tag_name }} ./velvet-${{ github.event.release.tag_name }}.zip

      - name: Upload Modrinth modpack
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.event.release.tag_name }} ./velvet-${{ github.event.release.tag_name }}.mrpack
