name: Update Mods

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Run daily at midnight UTC

permissions:
  contents: write
  pull-requests: write

jobs:
  update-mods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'

      - name: Install Packwiz
        run: go install github.com/packwiz/packwiz@latest

      - name: Refresh packwiz index
        run: packwiz refresh

      - name: Update mods
        run: packwiz update -y --all

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ github.token }}
          commit-message: "fix: update all mods"
          title: "fix: update all mods"
          body: |
            # Automated Mod Updates
            
            This pull request updates all mods to their latest versions.
            
            ## Changes
            - Updates all mods to their latest compatible versions
            - Refreshes the packwiz index
            
            Please review the changes before merging.
          branch: mod-updates
          base: main
          labels: "mod-updates,automated"
          reviewers: "${{ github.event.pusher.name }}"
